name: ants

on:
  push:
    paths:
      - recipes/*
      - recipes/ants/*
      - .github/workflows/ants.yml
      - .github/workflows/build.sh

  pull_request:
    paths:
      - recipes/*
      - recipes/ants/*
      - .github/workflows/ants.yml
      - .github/workflows/build.sh

env:
  APPLICATION: ants
  PYTHON_VER: 3.8
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Log into Github Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - name: Log into Dockerhub (optional)
        if: env.DOCKERHUB_REPO != ''
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Run Recipe and Image builder
        run: bash .github/workflows/build.sh
