name: Container Builder

on:
  push:
    paths:
      - itksnap/*
      - .github/workflows/container-builder.yml
  pull_request:
    paths:
      - itksnap/*
      - .github/workflows/container-builder.yml

env:
  DOCKERFILE: itksnap/Dockerfile
  IMAGEID: docker.pkg.github.com/${{ github.repository }}/itksnap_3.8.0:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Github Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Pull latest image
        run: docker pull ${{ env.IMAGEID }} || true
      - name: Build new image using cache
        run: docker build . --file ${{ env.DOCKERFILE }} --tag ${{ env.IMAGEID }} --cache-from ${{ env.IMAGEID }}
      - name: Push image to Github Package Registry
        run: docker push ${{ env.IMAGEID }}
