name: itksnap CI

on:

  push:
    paths:
      - itksnap/*
  pull_request:
    paths:
      - itksnap/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the latest Docker image
      run: docker build . --file itksnap/Dockerfile --tag vnmd/itksnap_3.8.0:latest
    - name: Push the latest Docker image
      run: docker push vnmd/itksnap_3.8.0:latest
