name: itksnap CI

on:

  push:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml
  pull_request:
    paths:
      - itksnap/*
      - .github/workflows/itksnap.yml

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Github Package Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Build the latest Docker image
      run: docker build . --file itksnap/Dockerfile --tag caid/itksnap_3.8.0:latest
    - name: Push image
      run: |
        IMAGE_NAME=itksnap_3.8.0:latest
        IMAGE_ID=docker.pkg.github.com/neurodesk/caid/$IMAGE_NAME
        VERSION=latest

        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
