name: singularity

on:
  push:
    paths:
      - singularity/*
      - .github/workflows/singularity.yml
 
  pull_request:
    paths:
      - singularity-docker/*
      - .github/workflows/singularity.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    - name: Pull latest build from Github Packages
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        IMAGEID=docker.pkg.github.com/$GITHUB_REPOSITORY/singularity
        IMAGEID=$(echo $IMAGEID | tr '[A-Z]' '[a-z]')
        {
          docker pull $IMAGEID \
            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID) \
            && echo "::set-env name=ROOTFS_CACHE::$ROOTFS_CACHE"
        } || echo "$IMAGEID not found. Resuming build..."
        echo "::set-env name=IMAGEID::$IMAGEID"
    - name: Build new image
      run: |
        SHORT_SHA=$(git rev-parse --short $GITHUB_SHA)
        docker build . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
        BUILDDATE=`date +%Y%m%d`
        echo "::set-env name=SHORT_SHA::$SHORT_SHA"
        echo "::set-env name=ROOTFS_NEW::$ROOTFS_NEW"
        echo "::set-env name=BUILDDATE::$BUILDDATE"
    - name: Push to Github packages (if changes found)
      if: env.GITHUB_REF != 'refs/heads/master' && env.ROOTFS_NEW != env.ROOTFS_CACHE
      run: |
        # Push to GH Packages
        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:$BUILDDATE
        docker tag $IMAGEID:$SHORT_SHA $IMAGEID:latest
        docker push $IMAGEID:latest
        docker push $IMAGEID:$BUILDDATE
